name: atomic_reaction
description: A library that helps implement reactive programming with the power of Dart Stream extended by the capabilities provided by the RxDart library.
version: 0.0.1
repository: https://github.com/alvarobcprado/atomic_reaction
issue_tracker: https://github.com/alvarobcprado/atomic_reaction/issues
homepage: https://github.com/alvarobcprado/atomic_reaction

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mocktail: ^1.0.2
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
